local L = LibStub("AceLocale-3.0"):NewLocale("GladiusEx", "enUS", true)

-- Cooldowns module
L["cat:pvp_trinket"] = "PvP Trinket"
L["cat:mass_dispel"] = "Mass Dispel"
L["cat:cc"] = "CC"
L["cat:offensive"] = "Offensive"
L["cat:defensive"] = "Defensive"
L["cat:silence"] = "Silence"
L["cat:interrupt"] = "Interrupt"
L["cat:dispel"] = "Dispel"
L["cat:heal"] = "Heal"
L["cat:knockback"] = "Knockback"
L["cat:stun"] = "Stun"
L["cat:immune"] = "Immune"
L["cat:talent"] = "Talent"
L["cat:uncat"] = "Uncategorized"
L["cat:covenant"] = "Covenant"
L["PvP Trinket Icon"] = true
L["Choose the PvP trinket icon style to display"] = true
L["Alliance (WotLK)"] = true
L["Alliance (Classic)"] = true
L["Horde (WotLK)"] = true
L["Horde (Classic)"] = true
L["Faction (Classic)"] = true
L["Faction (WotLK)"] = true
L["Gladiator (Retail)"] = true

-- Tags module
L["WARRIOR:short"] = "Warr"
L["DEATHKNIGHT:short"] = "DK"
L["WARLOCK:short"] = "Lock"
L["PRIEST:short"] = "Priest"
L["HUNTER:short"] = "Hunter"
L["ROGUE:short"] = "Rogue"
L["SHAMAN:short"] = "Shaman"
L["DRUID:short"] = "Druid"
L["PALADIN:short"] = "Pala"
L["MAGE:short"] = "Mage"
L["MONK:short"] = "Monk"
L["EVOKER:short"] = "Evoker"

L["specID:250:short"] = "Blood"
L["specID:251:short"] = "Frost"
L["specID:252:short"] = "Unholy"
L["specID:102:short"] = "Balance"
L["specID:103:short"] = "Feral"
L["specID:104:short"] = "Guardian"
L["specID:105:short"] = "Resto"
L["specID:253:short"] = "BM"
L["specID:254:short"] = "Marks"
L["specID:255:short"] = "Surv"
L["specID:62:short"] = "Arcane"
L["specID:63:short"] = "Fire"
L["specID:64:short"] = "Frost"
L["specID:268:short"] = "Brew"
L["specID:269:short"] = "Wind"
L["specID:270:short"] = "Mist"
L["specID:65:short"] = "Holy"
L["specID:66:short"] = "Prot"
L["specID:70:short"] = "Retri"
L["specID:256:short"] = "Disc"
L["specID:257:short"] = "Holy"
L["specID:258:short"] = "Shadow"
L["specID:259:short"] = "Assa"
L["specID:260:short"] = "Combat"
L["specID:261:short"] = "Subtl"
L["specID:262:short"] = "Ele"
L["specID:263:short"] = "Enha"
L["specID:264:short"] = "Resto"
L["specID:265:short"] = "Affli"
L["specID:266:short"] = "Demo"
L["specID:267:short"] = "Destru"
L["specID:71:short"] = "Arms"
L["specID:72:short"] = "Fury"
L["specID:73:short"] = "Prot"
L["specID:577:short"] = "Havoc"
L["specID:581:short"] = "Vengeance"
L["specID:1467:short"] = "Deva"
L["specID:1468:short"] = "Pres"
L["specID:1473:short"] = "Aug"

L["maxhealthTag"] = "Max Health"
L["maxpower:shortTag"] = "Max Power (Short)"
L["powerTag"] = "Power"
L["health:shortTag"] = "Health (Short)"
L["classTag"] = "Class"
L["class:shortTag"] = "Class (Short)"
L["power:percentageTag"] = "Power (%)"
L["power:roundedTag"] = "Power (%, rounded)"
L["power:shortTag"] = "Power (Short)"
L["raceTag"] = "Race"
L["nameTag"] = "Name"
L["name:statusTag"] = "Name/Status"
L["specTag"] = "Spec"
L["spec:shortTag"] = "Spec (Short)"
L["health:percentageTag"] = "Health (%)"
L["health:roundedTag"] = "Health (%, Rounded)"
L["healthTag"] = "Health"
L["maxhealth:shortTag"] = "Max Health (Short)"
L["maxpowerTag"] = "Max Power"
L["absorbsTag"] = "Absorbs"
L["absorbs:shortTag"] = "Absorbs (short)"
L["healthabsorbsTag"] = "Health plus Absorbs"
L["healthabsorbs:shortTag"] = "Health plus Absorbs (short)"
L["index0Tag"] = "0-indexed unit tag"
L["index1Tag"] = "1-indexed Unit tag"
L["unitTag"] = "Unit tag"

-- Module names
L["CastBar"] = "Cast Bar"
L["ClassIcon"] = "Class Icon"
L["DRTracker"] = "DR Tracker"
L["HealthBar"] = "Health Bar"
L["Tags"] = "Texts Tags"
L["PowerBar"] = "Power Bar"
L["TargetBar"] = "Target"
L["PetBar"] = "Pet"
L["SkillHistory"] = "Skill History"
L["Interrupts"] = true

-- Class names
L["Death Knight"] = true
L["Druid"] = true
L["Hunter"] = true
L["Mage"] = true
L["Paladin"] = true
L["Priest"] = true
L["Rogue"] = true
L["Shaman"] = true
L["Warlock"] = true
L["Warrior"] = true
L["Monk"] = true
L["Demon Hunter"] = true

-- General
L["Highlight player target"] = true
L["Show border around your target"] = true

L[" |T%s:20|t %s %s %s"] = true
L["%s settings"] = true
L["** If this is not your first run please lock or move the frame to prevent this from happening **"] = true
L["Absorbs bar color"] = true
L["Absorbs color"] = true
L["Absorbs settings"] = true
L["Absorbs"] = true
L["Action"] = true
L["Active"] = true
L["Add click action"] = true
L["Add cooldowns group"] = true
L["Add new aura filter"] = true
L["Add new aura"] = true
L["Add new cast"] = true
L["Add tag"] = true
L["Add text"] = true
L["Add"] = true
L["Adjust size to the frame size"] = true
L["Adjust size"] = true
L["Advanced font rendering"] = true
L["Advanced options"] = true
L["Alert animation settings"] = true
L["Alert animation"] = true
L["Alert color"] = true
L["Alert overlay color"] = true
L["Alert priority"] = true
L["Alerts"] = true
L["Align of the text"] = true
L["Alpha high"] = true
L["Alpha low"] = true
L["Alpha of the icon border while the spell is being used"] = true
L["Alpha of the icon border while the spell is not on cooldown"] = true
L["Alpha of the icon border while the spell is on cooldown"] = true
L["Alpha of the icon while the spell is being used"] = true
L["Alpha of the icon while the spell is not on cooldown"] = true
L["Alpha of the icon while the spell is on cooldown"] = true
L["alt-"] = true
L["Anchor of the frame"] = true
L["Anchor"] = true
L["Animation ease function"] = true
L["Animation ease method"] = true
L["Animation ease mode"] = true
L["Announcement toggles"] = true
L["Announcements"] = true
L["Announces when an enemy drops below a certain health threshold"] = true
L["Announces when an enemy tries to resurrect a teammate"] = true
L["Announces when enemies sit down to drink"] = true
L["Announces when the spec of an enemy was detected"] = true
L["Apply filter to"] = true
L["Arena"] = true
L["Attach text to module bar"] = true
L["Attach to the given frame"] = true
L["Attach to"] = true
L["Aura name"] = true
L["Auras alerts"] = true
L["Auras per row"] = true
L["Auras"] = true
L["Available"] = true
L["Background color"] = true
L["Background padding"] = true
L["Bar height"] = true
L["Bar order"] = true
L["Bar settings"] = true
L["Bar texture"] = true
L["Bar width"] = true
L["Bar"] = true
L["Bars height"] = true
L["Blacklist"] = true
L["Blend mode"] = true
L["Blend"] = true
L["Hide background out of cast"] = true
L["Hides the background when the unit is not casting. If in \"Inside Frame\" mode, will still show the frame's background."] = true
L["Blizzard's Floating Combat Text"] = true
L["Border color for spells in this category"] = true
L["Border size"] = true
L["Border transparency settings"] = true
L["Border transparency"] = true
L["Both"] = true
L["Bottom left"] = true
L["Bottom right"] = true
L["Bottom"] = true
L["Buffs"] = true
L["Button 4"] = true
L["Button 5"] = true
L["Cast spell"] = true
L["Cast text"] = true
L["Cast time text"] = true
L["Casts alerts"] = true
L["Casts"] = true
L["Categories"] = true
L["Category settings"] = true
L["Category"] = true
L["Center left"] = true
L["Center right"] = true
L["Center"] = true
L["Charges: %i"] = true
L["Covenant: %s"] = true
L["Choose how low an enemy must be before low health is announced"] = true
L["Choose how your announcements are displayed"] = true
L["Class color"] = true
L["Class icon"] = true
L["Class"] = true
L["ClassIcon"] = true
L["Click actions"] = true
L["Clicks"] = true
L["Color of the background"] = true
L["Color of the cast bar background"] = true
L["Color of the cast bar when the spell can't be interrupted"] = true
L["Color of the cast bar"] = true
L["Color of the frame background"] = true
L["Color of the frames background"] = true
L["Color of the gloss"] = true
L["Color of the health bar background"] = true
L["Color of the health bar"] = true
L["Color of the highlight"] = true
L["Color of the power bar background"] = true
L["Color of the power bar"] = true
L["Color of the text"] = true
L["Color"] = true
L["Cooldown reverse"] = true
L["Cooldown spiral"] = true
L["Cooldown starts on dispel"] = true
L["Cooldown starts when aura fades"] = true
L["Cooldowns group %s"] = true
L["Cooldowns"] = true
L["DR-Colored Border"] = true
L["DR Text"] = true
L["Adds a border to the icon the color of which will be the DR color"] = true
L["Copy all settings from arena to party"] = true
L["Copy all settings from party to arena"] = true
L["Copy from arena"] = true
L["Copy from party"] = true
L["Copy cooldown spells from the party with the same cooldown group name"] = true
L["Copy cooldown spells from the arena with the same cooldown group name"] = true
L["No matching group"] = true
L["Copy settings"] = true
L["Crop borders"] = true
L["ctrl-"] = true
L["Cubic"] = true
L["Dead alpha"] = true
L["DEAD"] = true
L["Debuffs"] = true
L["Decrease the priority of spells in this category"] = true
L["Default color"] = true
L["Delete click action"] = true
L["Delete tag"] = true
L["Delete text"] = true
L["Delete"] = true
L["Destination"] = true
L["Detach the group from the unit frames, showing the cooldowns of all the units and allowing you to move it freely"] = true
L["Detached group"] = true
L["Disable all the spells in this category"] = true
L["Disable all the spells"] = true
L["Disable all"] = true
L["Disable this if you are experiencing problems with the texts (requires a UI reload to take effect)"] = true
L["Disable this to be able to move the frames separately"] = true
L["Disable"] = true
L["Disabled"] = true
L["Display the cooldown spiral for the drTracker icons"] = true
L["Display the cooldown spiral for the important auras"] = true
L["Down left"] = true
L["Down right"] = true
L["Down"] = true
L["Drinking"] = true
L["DRINKING: %s (%s)"] = true
L["DRTracker"] = true
L["Duration of each animation cycle, in seconds"] = true
L["Duration of the enter animation, in seconds"] = true
L["Duration of the fade out animation, in seconds"] = true
L["Duration"] = true
L["Duration: %is"] = true
L["Ease function"] = true
L["Ease mode"] = true
L["Ease"] = true
L["Enable all the spells in this category"] = true
L["Enable all the spells"] = true
L["Enable all"] = true
L["Enable module"] = true
L["Enemy spec: %s (%s/%s)"] = true
L["Enlarge mine"] = true
L["Enlarge mine"] = true
L["Ordering"] = true
L["Higher prio first"] = true
L["Show buffs with a higher priority level at the beginning"] = true
L["Enlarged scale"] = true
L["Enter animation settings"] = true
L["Enter animation"] = true
L["Events which update the tag"] = true
L["Events"] = true
L["Example Spell Name"] = true
L["Fade out duration"] = true
L["Filter type"] = true
L["Filters"] = true
L["First run has been detected, displaying test frame"] = true
L["Font outline"] = true
L["Font settings"] = true
L["Font shadow color"] = true
L["Font size"] = true
L["Font"] = true
L["Font"] = true
L["Frame background color"] = true
L["Frame grouping"] = true
L["Frame height"] = true
L["Frame level of the frame"] = true
L["Frame level"] = true
L["Frame scale"] = true
L["Frame width"] = true
L["Frame"] = true
L["Function"] = true
L["General settings"] = true
L["General"] = true
L["General"] = true
L["GladiusEx Enemy Anchor - click to move"] = true
L["GladiusEx Party Anchor - click to move"] = true
L["Global font size"] = true
L["Global font, used by the modules"] = true
L["Global settings"] = true
L["Global texture of the bars"] = true
L["Gloss color"] = true
L["Gloss"] = true
L["Group %i anchor (%s)"] = true
L["Group background color"] = true
L["Group by unit"] = true
L["Group unit frames"] = true
L["Group"] = true
L["Grouping"] = true
L["Grow direction of the icons"] = true
L["Grow direction"] = true
L["HealthBar"] = true
L["Height of the bars"] = true
L["Height of the cast bar"] = true
L["Height of the health bar"] = true
L["Height of the power bar"] = true
L["Height"] = true
L["Hide talents until detected"] = true
L["High transparency alpha value of the animation"] = true
L["Highlight border width"] = true
L["Highlight color"] = true
L["Highlight focus target"] = true
L["Highlight frame on mouseover"] = true
L["Highlight on mouseover"] = true
L["Highlight raid assist target"] = true
L["Highlight"] = true
L["Horizontal padding of the icons"] = true
L["Horizontal padding"] = true
L["Horizontal spacing of the icons"] = true
L["Horizontal spacing"] = true
L["Hover settings"] = true
L["Hover"] = true
L["How much the absorbs bar can grow outside the health bar, as a proportion of the unit's total health"] = true
L["How much the incoming heals bar can grow outside the health bar, as a proportion of the unit's total health"] = true
L["Icon border size"] = true
L["Icon position"] = true
L["Icon size"] = true
L["Icon transparency settings"] = true
L["Icon transparency"] = true
L["Icon"] = true
L["Icons max"] = true
L["Icons per column"] = true
L["Important auras"] = true
L["If toggled, the important aura with the lowest remaining duration will be showed if there is a tie in priority"] = true
L["In"] = true
L["In-Out"] = true
L["Incoming heals bar color"] = true
L["Incoming heals color"] = true
L["Incoming heals settings"] = true
L["Incoming heals"] = true
L["Increase the priority of spells in this category"] = true
L["Inside frame"] = true
L["Inverse"] = true
L["Invert the bar colors"] = true
L["Invert the dark/bright part of the cooldown spiral"] = true
L["Items"] = true
L["Left and right"] = true
L["Left bottom"] = true
L["Left top"] = true
L["Left"] = true
L["Lock frames"] = true
L["Lock the frames to hide"] = true
L["Lock the group to hide"] = true
L["Locked"] = true
L["Low health alert"] = true
L["Low health settings"] = true
L["Low health threshold"] = true
L["Low health threshold"] = true
L["Low health"] = true
L["Low health"] = true
L["LOW HEALTH: %s (%s)"] = true
L["Low transparency alpha value of the animation"] = true
L["Margin between each button"] = true
L["Margin between each module"] = true
L["Margin"] = true
L["Max number of rows"] = true
L["Middle"] = true
L["MikScrollingBattleText"] = true
L["Minimum health percent to fire the alert"] = true
L["Mod margin"] = true
L["Modifier"] = true
L["Mouse button"] = true
L["Name of the aura"] = true
L["Name of the aura"] = true
L["Name of the cast spell"] = true
L["Name of the cast"] = true
L["Name of the tag"] = true
L["Name of the text element"] = true
L["Name"] = true
L["New aura"] = true
L["New cast"] = true
L["None"] = true
L["Not interruptible color"] = true
L["Number of auras per row"] = true
L["Number of icons per column"] = true
L["Number of max icons"] = true
L["Number of rows"] = true
L["OFFLINE"] = true
L["Offset X"] = true
L["Offset Y"] = true
L["On cooldown"] = true
L["Options"] = true
L["Out of range alpha"] = true
L["Out"] = true
L["Outline"] = true
L["Outside bar limit"] = true
L["Overlay blend mode"] = true
L["Padding of the background"] = true
L["Parrot"] = true
L["Party"] = true
L["Pet"] = true
L["Player focus target settings"] = true
L["Player focus target"] = true
L["Player target settings"] = true
L["Player target"] = true
L["Portrait 2D"] = true
L["Portrait 3D"] = true
L["Position of the cast bar icon"] = true
L["Icon Offset X"] = true
L["Icon Offset Y"] = true
L["X offset of the icon"] = true
L["Y offset of the icon"] = true
L["Position of the class icon"] = true
L["Position of the frame"] = true
L["Position settings"] = true
L["Position"] = true
L["Power type"] = true
L["PowerBar"] = true
L["Priority of the highlight"] = true
L["Priority"] = true
L["Quadratic"] = true
L["Race"] = true
L["Raid assist settings"] = true
L["Raid assist target"] = true
L["Raid target icon %i"] = true
L["Raid target icons"] = true
L["Raid Warning"] = true
L["Relative point of the frame"] = true
L["Relative point"] = true
L["Remaining time"] = true
L["Remove this cooldowns group"] = true
L["Replaces: %s"] = true
L["Required aura: %s"] = true
L["Reset all arena settings to their default values"] = true
L["Reset all party settings to their default values"] = true
L["Reset arena settings"] = true
L["Reset module"] = true
L["Reset party settings"] = true
L["Reset settings"] = true
L["Resets: %s"] = true
L["RESURRECTING: %s (%s)"] = true
L["Resurrection"] = true
L["Right bottom"] = true
L["Right top"] = true
L["Right"] = true
L["Role"] = true
L["Say"] = true
L["Scale of the enlarged auras"] = true
L["Scale of the frame"] = true
L["Scrolling Combat Text"] = true
L["Select a modifier for this click action"] = true
L["Select what priority the alert should have - higher equals more priority"] = true
L["Select what priority the aura should have - higher equals more priority"] = true
L["Select what priority the aura should have - higher equals more priority"] = true
L["Select what priority the cast should have - higher equals more priority"] = true
L["Select what this click action does"] = true
L["Select which mouse button this click action uses"] = true
L["Self"] = true
L["Shared cooldown: %s (%is)"] = true
L["Shield icon"] = true
L["shift-"] = true
L["Show absorbs"] = true
L["Show border around your focus target"] = true
L["Show border around raid assist"] = true
L["Show border around raid target %i"] = true
L["Show Buffs"] = true
L["Show cast time"] = true
L["Show Debuffs"] = true
L["Show delay"] = true
L["Show DRs on start instead of on refresh/removal"] = true
L["Show important auras instead of the class icon"] = true
L["Show important aura with least time left"] = true
L["Show incoming heals"] = true
L["Show on Apply"] = true
L["Show only dispellable"] = true
L["Show only mine"] = true
L["Show party frames"] = true
L["Show arena frames"] = true
L["Show the current DR on the icon as text"] = true
L["Toggle to show your arena frames"] = true
L["Show spark"] = true
L["Show tooltips"] = true
L["Show total time"] = true
L["Show"] = true
L["Size of the aura icons"] = true
L["Size of the cooldown icon borders"] = true
L["Size of the cooldown icons"] = true
L["Size of the frames border"] = true
L["Size of the icons"] = true
L["Size of the text"] = true
L["Size settings"] = true
L["Size"] = true
L["Space between the icons"] = true
L["Spacing"] = true
L["Spec detection"] = true
L["Spec"] = true
L["Spell name / Macro text"] = true
L["Spell name"] = true
L["Stealth alpha"] = true
L["Stop testing"] = true
L["Tag settings"] = true
L["Tag"] = true
L["Tag: %s"] = true
L["Talent"] = true
L["TargetBar"] = true
L["Test 2v2"] = true
L["Test 3v3"] = true
L["Test 5v5"] = true
L["Test frames"] = true
L["Test units"] = true
L["Testing settings"] = true
L["Testing"] = true
L["Text align of the cast text"] = true
L["Text align of the cast time text"] = true
L["Text align"] = true
L["Text color of the cast text"] = true
L["Text color of the cast time text"] = true
L["Text color"] = true
L["Text outline of the global font"] = true
L["Text settings"] = true
L["Text shadow color of the global font"] = true
L["Text size of the cast text"] = true
L["Text size of the cast time text"] = true
L["Text size of the DR text"] = true
L["Text size of the global font"] = true
L["Text size of the global font"] = true
L["Text size"] = true
L["Text to be displayed"] = true
L["Text"] = true
L["Texts"] = true
L["Texture of the cast bar"] = true
L["Texture of the health bar"] = true
L["Texture of the power bar"] = true
L["Texture"] = true
L["The direction you want the frames to grow in"] = true
L["Thick outline"] = true
L["Timeout settings"] = true
L["Timeout"] = true
L["Timeout, in seconds"] = true
L["Toggle alerts when some auras are active"] = true
L["Toggle alerts when some spells are being cast"] = true
L["Hide cast alerts on self"] = true
L["Group name"] = true
L["Hide cast alerts on your own frame when you are casting alert-worthy spells"] = true
L["Toggle aura buffs"] = true
L["Toggle aura debuffs"] = true
L["Toggle cast text"] = true
L["Toggle cast time text"] = true
L["Toggle cast time"] = true
L["Toggle default color"] = true
L["Toggle delay"] = true
L["Toggle display of absorbs in the health bar"] = true
L["Toggle display of advanced options"] = true
L["Toggle display of incoming heals in the health bar"] = true
L["Toggle gloss on the icon"] = true
L["Toggle health bar class color"] = true
L["Toggle if the auras should show the aura tooltip when hovered"] = true
L["Toggle if the cooldowns in the detached group should be grouped by unit"] = true
L["Toggle if the detached group can be moved"] = true
L["Toggle if the frames can be moved"] = true
L["Toggle if the icon borders should be cropped or not"] = true
L["Toggle if the icons should show the spell tooltip when hovered"] = true
L["Toggle if you want the cast bar to be part of the frame or if you want to position it freely"] = true
L["Toggle if your auras should be enlarged"] = true
L["Toggle low health alerts"] = true
L["Toggle remaining time instead of cast time"] = true
L["Toggle the cast bar shield icon for not interruptible spells"] = true
L["Toggle the cast bar spark"] = true
L["Toggle the cast bar spell icon"] = true
L["Toggle the class icon"] = true
L["Toggle to show your party frames"] = true
L["Toggle total time"] = true
L["Top left"] = true
L["Top right"] = true
L["Top"] = true
L["Transparency for dead units"] = true
L["Transparency for units in stealth"] = true
L["Transparency for units out of range"] = true
L["Transparency settings"] = true
L["Transparency settings"] = true
L["Transparency"] = true
L["Transparency"] = true
L["Unit frames settings"] = true
L["Unit frames"] = true
L["Unit power type"] = true
L["Unit race"] = true
L["Unit talent specialization"] = true
L["Up and down"] = true
L["Up left"] = true
L["Up right"] = true
L["Up"] = true
L["Use global texture"] = true
L["Use the global bar texture"] = true
L["Use the global font size"] = true
L["Valid slash commands are:"] = true
L["Vertical padding of the icons"] = true
L["Vertical padding"] = true
L["Vertical spacing of the icons"] = true
L["Vertical spacing"] = true
L["Welcome to GladiusEx!"] = true
L["What auras to filter"] = true
L["When available, show specialization instead of class icons"] = true
L["Whitelist"] = true
L["Widget settings"] = true
L["Widget"] = true
L["Width of the bars"] = true
L["Width of the cast bar"] = true
L["Width"] = true
L["X offset of the cast text"] = true
L["X offset of the cast time text"] = true
L["X offset of the frame"] = true
L["X offset"] = true
L["Y offset of the cast text"] = true
L["Y offset of the cast time text"] = true
L["Y offset of the frame"] = true
L["Y offset"] = true
L["Hide self frame"] = true
L["Hide the player's frame"] = true
L["Covenant"] = true
L["How long should the scale animation last"] = true
L["The size the the icon should scale up to when the cooldown goes off CD"] = true
L["The size the the icon should scale up to when the cooldown gets used"] = true
L["Off-cooldown scale duration"] = true
L["Off-cooldown scale"] = true
L["On-use scale duration"] = true
L["On-use scale"] = true
L["Animation settings on event"] = true
L["Add new aura order"] = true
L["Animation"] = true
L["Appearance"] = true
L["Appearance settings"] = true
L["Show swipe"] = true
L["Show cooldown swipe on buffs"] = true
L["Show cooldown swipe on debuffs"] = true
L["Reverse swipe"] = true
L["Reverse swipe animation"] = true
L["Swipe color"] = true
L["Cooldown swipe color on buffs"] = true
L["Cooldown swipe color on debuffs"] = true
L["Glow cooldowns that are in active use"] = true
L["Show a glow around the cooldown icon during the cooldown duration"] = true
L["Side-view icon"] = true
L["Shows a secondary side-icon so you can keep seeing the class/role/spec while an important aura is active"] = true
L["Enable"] = true
L["Side-view icon size"] = true
L["Vertical offset"] = true
L["Vertical offset"] = true
