name: Package and release

on:
  push:
    tags: "**"
    branches: "master"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }} # "GITHUB_TOKEN" is a secret always provided to the workflow

    steps:
      - name: Clone project
        uses: actions/checkout@v1

      # Run the GitHub Action for the packager project
      - name: Package and release
        uses: BigWigsMods/packager@master
